### PR TITLE
Info about my talk

### PR DESCRIPTION
**Pull request by sennoma**

### CODE REVIEW

**Comment by sergey-platonov** [comment]
Please, add info about speaker in speaker_about.md.
Thank you!

**Review by sergey-platonov — CHANGES_REQUESTED** [review]
Please, add info about speaker in speaker_about.md.
Thank you!

**Comment by sennoma** [comment]
Done

**Comment by sergey-platonov** [comment]
Thank you!

**Review by sergey-platonov — APPROVED** [review]

**Pull request merged**
